//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Breed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Breed()
        {
            this.Animal = new HashSet<Animal>();
        }
    
        public int BreedId { get; set; }
        public string Name { get; set; }
        public string Synonym { get; set; }
        public string Code { get; set; }
        public string WFCStatusCode { get; set; }
        public string Group { get; set; }
        public string Section { get; set; }
        public string EnglishName { get; set; }
        public string Variety { get; set; }
        public Nullable<int> StandartFCI { get; set; }
        public Nullable<int> RCF { get; set; }
        public string URLPhoto { get; set; }
        public string URLWiki { get; set; }
        public Nullable<int> YearOfRecognitionFCI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animal { get; set; }
        public virtual WCFStatus WCFStatus { get; set; }
        public virtual BreedStatistic BreedStatistic { get; set; }
    }
}
