//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int DonationId { get; set; }
        public System.DateTime DateOfDonation { get; set; }
        public int ClientId { get; set; }
        public int FoodId { get; set; }
        public int Amount { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Food Food { get; set; }
    }
}
