//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.Donation = new HashSet<Donation>();
            this.InputFoods = new HashSet<InputFoods>();
            this.InputFoods1 = new HashSet<InputFoods>();
            this.FoodPortion = new HashSet<FoodPortion>();
        }
    
        public int FoodId { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string FoodClass { get; set; }
        public Nullable<bool> IsHistoricalReference { get; set; }
        public Nullable<int> NdbNumber { get; set; }
        public string FoodCategory { get; set; }
        public Nullable<int> FdcId { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public string Scientificname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputFoods> InputFoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputFoods> InputFoods1 { get; set; }
        public virtual FoodAttribute FoodAttribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodPortion> FoodPortion { get; set; }
    }
}
