//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodNutrientDerivation
    {
        public int FoodNutrientDerivationCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> FoodNutrientSourceId { get; set; }
    
        public virtual FoodNutrientSource FoodNutrientSource { get; set; }
    }
}
