//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodPortion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodPortion()
        {
            this.Food = new HashSet<Food>();
        }
    
        public int FoodPortionId { get; set; }
        public Nullable<int> Value { get; set; }
        public string MeasureUnitName { get; set; }
        public string MeasureUnitAbbreviation { get; set; }
        public string Modifier { get; set; }
        public Nullable<decimal> GramWeight { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<int> MinYearAcquired { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food> Food { get; set; }
    }
}
