//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputFoods
    {
        public int FoodId { get; set; }
        public string Description { get; set; }
        public int InputFoodId { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Food Food1 { get; set; }
    }
}
