//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutrientConversionFactor
    {
        public int NutrientConversionFactorId { get; set; }
        public Nullable<decimal> ProteinValue { get; set; }
        public Nullable<decimal> FatValue { get; set; }
        public Nullable<decimal> CarbohydrateValue { get; set; }
    }
}
