//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nutrient
    {
        public int NutrientId { get; set; }
        public Nullable<int> Number { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rank { get; set; }
        public string UnitName { get; set; }
    }
}
