//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakingAnimal
    {
        public int TakingAnimalId { get; set; }
        public int ClientId { get; set; }
        public int AnimalId { get; set; }
        public System.DateTime DateOfTaking { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Client Client { get; set; }
    }
}
